spring.application.name=livebflow-calculadora

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Server Configuration
server.servlet.context-path=/
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
